version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna
      MYSQL_PASSWORD: lavagna
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - back_net
     

  lavagna:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/lavagna
      - DATASOURCE_USERNAME=lavagna
      - DATASOURCE_PASSWORD=lavagna
      - SPRING_PROFILE_ACTIVE=prod
    entrypoint: ["/app/entrypoint.sh"]
    networks:
      - front_net
      - back_net

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./project/src/main/webapp:/usr/share/nginx/html
      - ./target/lavagna/help:/usr/share/ngnix/html
    ports:
      - "80:80"
    networks:
      - front_net
     
volumes:
  mysql-data:
networks:
  front_net:
  back_net:
