version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lavagna
      MYSQL_USER: lavagna
      MYSQL_PASSWORD: lavagna
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  lavagna:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/lavagna
      - DATASOURCE_USERNAME=lavagna
      - DATASOURCE_PASSWORD=lavagna
      - SPRING_PROFILE_ACTIVE=prod
    entrypoint: ["/app/entrypoint.sh"]

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure this path points to the nginx.conf file
      - ./project/src/main/webapp:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  mysql-data:
